### Health check
GET http://localhost:5000/

### Get all users

GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Andrei",
  "username": "bmoood",
  "email": "andrei@example.com",
  "password": "passwor"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "identifier": "bmoood",
  "password": "password123"
}

###

POST http://localhost:5000/api/auth/refresh

###

POST http://localhost:5000/api/auth/logout